# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=512)),
                ('bag_minids', models.TextField()),
                ('transfer_token', models.CharField(max_length=64)),
            ],
        ),
    ]
