# Generated by Django 2.0 on 2018-01-05 23:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('api', '0002_stagebag'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobusUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='bag',
            name='user',
            field=models.ForeignKey(default='3b843349-4d4d-4ef3-916d-2a465f9740a9', on_delete=django.db.models.deletion.CASCADE, to='api.GlobusUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagebag',
            name='user',
            field=models.ForeignKey(default='3b843349-4d4d-4ef3-916d-2a465f9740a9', on_delete=django.db.models.deletion.CASCADE, to='api.GlobusUser'),
            preserve_default=False,
        ),
    ]
