# Generated by Django 3.0.8 on 2020-07-14 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_minid_to_identifier_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeToken',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True,
                                        serialize=False)),
                ('scope', models.CharField(max_length=128)),
                ('issued_at', models.FloatField()),
                ('expires_at', models.FloatField()),
                ('last_introspection', models.FloatField()),
                ('dependent_tokens_cache', models.TextField(blank=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bag',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stagebag',
            name='destination_path_prefix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stagebag',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='stagebags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TokenStore',
        ),
    ]
