# Generated by Django 2.0.7 on 2018-08-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180724_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagebag',
            name='transfer_token',
        ),
    ]
