# Generated by Django 3.0.8 on 2020-08-11 16:19
# Beginning of migration from original minid minting concierge service to Manifest Concierge Service

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0001_initial'),
        ('api', '0007_transfer_transfermanifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfermanifest',
            name='action',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='gap.Action'),
        ),
    ]
