# Generated by Django 3.0.8 on 2020-09-10 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_transfer_transfermanifest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='bags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestTransfer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('action', models.ForeignKey(blank=True, null=True,
                                             on_delete=django.db.models.deletion.SET_NULL, to='gap.Action')),
                ('manifest', models.ForeignKey(blank=True, null=True,
                                               on_delete=django.db.models.deletion.CASCADE, to='api.Manifest')),
            ],
        ),
        migrations.RemoveField(
            model_name='stagebag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transfermanifest',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='transfermanifest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='id',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='task_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
        migrations.DeleteModel(
            name='StageBag',
        ),
        migrations.DeleteModel(
            name='TransferManifest',
        ),
        migrations.AddField(
            model_name='manifesttransfer',
            name='transfers',
            field=models.ManyToManyField(to='api.Transfer'),
        ),
        migrations.AddField(
            model_name='manifesttransfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='manifests', to=settings.AUTH_USER_MODEL),
        ),
    ]
