# Generated by Django 3.0.8 on 2020-08-18 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_transfermanifest_action'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bag',
            new_name='Manifest',
        ),
    ]
