# Generated by Django 3.0.8 on 2020-08-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200818_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='minid',
        ),
    ]
