# Generated by Django 3.0.8 on 2020-08-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_manifest_minid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
