# Generated by Django 3.0.8 on 2020-09-15 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField(auto_now_add=True, max_length=256)),
                ('completion_time', models.DateTimeField(max_length=256, null=True)),
                ('release_after', models.CharField(default='P30D', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=256)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.Action')),
            ],
        ),
    ]
