# Generated by Django 3.0.8 on 2020-08-06 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=256)),
                ('request_id', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('display_status', models.CharField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE'), (2, 'SUCCEEDED'), (3, 'FAILED'), (4, 'RELEASED')], default=1, max_length=2)),
                ('start_time', models.DateTimeField(auto_now_add=True, max_length=256)),
                ('completion_time', models.DateTimeField(auto_now_add=True, max_length=256)),
                ('release_after', models.CharField(default='P30D', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=256)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.Action')),
            ],
        ),
    ]
