# Generated by Django 3.1.2 on 2020-10-27 16:31

from django.db import migrations, models
import globus_action_provider_tools.data_types


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobusURN',
            fields=[
                ('urn', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='action',
            old_name='user',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='action',
            name='display_status',
            field=models.CharField(default=globus_action_provider_tools.data_types.ActionStatusValue['INACTIVE'], max_length=32),
        ),
        migrations.AlterField(
            model_name='action',
            name='release_after',
            field=models.IntegerField(default=2592000),
        ),
        migrations.AddField(
            model_name='action',
            name='manager_by',
            field=models.ManyToManyField(related_name='manager_by', to='gap.GlobusURN'),
        ),
        migrations.AddField(
            model_name='action',
            name='monitor_by',
            field=models.ManyToManyField(related_name='monitor_by', to='gap.GlobusURN'),
        ),
    ]
