# Generated by Django 3.1.2 on 2020-11-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0002_auto_20201027_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='manager_by',
        ),
        migrations.RemoveField(
            model_name='action',
            name='monitor_by',
        ),
        migrations.AlterField(
            model_name='action',
            name='request_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='TestAction',
        ),
    ]
